# -*- coding: utf-8 -*-
"""hola_mundo_st.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKFy3MyklB7ngsA-CCnze9YhZfX7Zf60
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')